server:
  port: 8452

# DataSource Config
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://47.96.39.78:3399/zw?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    #    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    async:
      request-timeout: 3000