server:
  port: 8452

# DataSource Config
#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.223.66:3306/wk_wfj?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    #    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  mvc:
#    async:
#      request-timeout: 3000
#  redis:
#    host: 192.168.223.66
#    port: 6379

spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://cff.w369m.top:13306/wk_wfj?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
          username: root
          password: admin123
          driver-class-name: com.mysql.cj.jdbc.Driver
#        slaver:
#          url: jdbc:mysql://192.168.223.66:3306/wk_wfj2?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#          username: root
#          password: root
#          driver-class-name: com.mysql.cj.jdbc.Driver
#        pgsql:
#          url: jdbc:postgresql://192.168.223.66:5432/postgres?currentSchema=public
#          username: postgres
#          password: root
#          driver-class-name: org.postgresql.Driver
    mvc:
      async:
        request-timeout: 3000
      pathmatch:
        matching-strategy: ant_path_matcher

  redis:
    host: cff.w369m.top
    port: 16379
    password: 123456
# 整合mybatis
mybatis:
  #  typeAliasesPackage: com.neuedu.entity
  mapper-locations: classpath*:mapper/*.xml

